### ISSUE TITLE
phase 3 crosses meta data - release bucket version incorrect

### ISSUE THREAD

**Issue by cclarkson** [malariagen/ag1000g-phase3-data-paper#32]
Crosses meta data in the release bucket does not match the file [here](https://github.com/malariagen/vector-ops/blob/master/tracking/AG1000G-X/cross.samples.meta.txt) - the 'cross' column is missing. 

**update**
There is some confusion here. @hardingnj, the file you linked in your email (see above) is actually the phase2 crosses meta data, I don't know what is doing in vector_ops - we really need to put the phase in the file names!

There is a [file](https://github.com/malariagen/vector-ops/blob/master/tracking/AG1000G-X/crosses.tsv) in vector_ops, however, that looks more helpful - I will see how this compares with the crosses genotypes for number of samples. 

Either way, we still don't have an up to date cross meta data file in the release bucket.

**Comment by hardingnj** [comment]
https://storage.cloud.google.com/vo_agam_staging/v3/metadata/crosses/samples.crosses.csv?authuser=1

**Comment by hardingnj** [comment]
re **https://github.com/malariagen/vector-ops/pull/1256**

**Comment by cclarkson** [comment]
fixed via malariagen/vector-ops#1256
