### ISSUE TITLE
Manubot workflow run failure

### ISSUE THREAD

**Issue by leehart** [malariagen/ag1000g-phase3-data-paper#48]
From https://github.com/malariagen/ag1000g-phase3-data-paper/actions/runs/355697703
___
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files.

The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files.
___

GitHub Actions: Deprecating set-env and add-path commands
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by hardingnj** [comment]
Thanks Lee. Though I'm confused- if not disabled until 16th November- why are we getting build fails now?

**Comment by leehart** [comment]
I don't know yet. Maybe they decided to run ahead of schedule "out of an abundance of caution", because it's a security vulnerability. I suppose users are more likely to act on a failing error than respond to a mere warning or security suggestion.

**Comment by leehart** [comment]
https://github.com/manubot/rootstock/issues/388

**Comment by leehart** [comment]
The fix looks very straight-forward, so we won't have to wait for upstream https://github.com/manubot/rootstock/pull/389/files

**Comment by leehart** [comment]
Closed by merged PR #52
